version: '3.8'

services:
  tester:
    build:
      context: .
      dockerfile: tester/Dockerfile
    image: localhost/ojdbc-connection-tester
    environment:
      DB_CONNECTION_STRING: ${MY_DB_CONNECTION_STRING}
      DB_USER: ${MY_DB_USER}
      DB_PASSWORD: ${MY_DB_PASSWORD}
    volumes:
      - ./wallet/tnsnames.ora:/etc/tnsnames.ora:ro


