version: '3.8'

services:
  ojdbc-cli:
    volumes:
      - ./wallet/cwallet.sso:/etc/cwallet.sso:ro
      - ./wallet/ewallet.p12:/etc/ewallet.p12:ro
      - ./wallet/tnsnames.ora:/etc/tnsnames.ora:ro
