version: '3.8'

services:
  tester:
    environment:
      DB_CONNECTION_STRING: "${MY_CONNECTION_PREFIX}${MY_DB_CONNECTION_STRING}"
      DB_USER: ""
      DB_PASSWORD: ""
      USE_WALLET: 1
    volumes:
        - ./wallet/cwallet.sso:${MY_TNS_ADMIN:-/etc}/cwallet.sso:ro
        - ./wallet/ewallet.p12:${MY_TNS_ADMIN:-/etc}/ewallet.p12:ro
