#!/bin/bash

CREDENTIAL_OPTS=
if [[ -n $DB_USER ]] ; then
  CREDENTIAL_OPTS="${CREDENTIAL_OPTS} -u ${DB_USER}"
fi

if [[ -n $DB_PASSWORD ]] ; then
  CREDENTIAL_OPTS="${CREDENTIAL_OPTS} -p ${DB_PASSWORD}"
fi

exec "${JAVACMD}" -cp ${CLASSPATH} ch.demirole.OjdbcTester.App \
    ${CREDENTIAL_OPTS} \
    -c "jdbc:oracle:thin:${DB_CONNECTION_STRING}?TNS_ADMIN=/etc" \
    "$1"
